### ISSUE TITLE
apt upgrade removes the example version info inside /etc/os-release 

### ISSUE THREAD

**Issue by BaochengSu** [siemens/meta-iot2050#247]
The `isar/meta/classes/image-postproc-extension.bbclass` appends `BUILD_ID`, `VARIANT`,  and `ISAR_IMAGE_VERSION` to `/etc/os-release`.

However an `apt upgrade` command removes these appendix values.

Unfortunately the firmware updating package depends on these values...:thinking:

**Comment by jan-kiszka** [comment]
/etc/os-release is owned by base-files. So, any update of that package will change what our image generation left behind - only fair, the image is no longer originally ours.

Same applies to the image-based firmware update scenario: any package-based modification on the image is naturally overwritten when the next image version is installed. Once we enable secure boot in combination with swupdate, it will even become impossible to overwrite packages because that will invalidate the integrity of the image, and we will mount the majority of the image read-only for that reason.

Still, we need some countermeasure for the current swupdate setup, that's true. @gylstorffq, any ideas?

**Comment by jan-kiszka** [comment]
...can be as simple as explaining the concept more clearly in the README: Image-based updates excluded packages-based one - don't use apt anymore.

**Comment by gylstorffq** [comment]
@BaochengSu  @jan-kiszka  If I read this correctly this is for updating the firmware from  TI or U-boot with `recipes-app/iot2050-firmware-update`,   not the Image with SWUpdate. The implementation of SWUpdate doesn't relay on /etc/os-release. I think we should move these information in a seperate file under `/etc/`.

**Comment by jan-kiszka** [comment]
Ah, misunderstanding of mine.

**Comment by Webbeh** [comment]
How about adding a new variable for this to the u-boot environment ? 

Those won't be reset by anything the user does in the OS itself (through apt or anything else) and will help you once the image is actually going read-only.

**Comment by jan-kiszka** [comment]
We have subtle dependencies between firmware version and kernel versions, at least for this current update case (hopefully, the future will all be bright, and this will never happen again). That motivated to also check if the update-triggering image version will still be able to boot after the update, thus is compatible. This is also important as many users do not have the debug port attached and will therefore not be able to read error messages from a boot of an incompatible image - to box will appear "bricked".

The current issue can still be resolved by a user via booting from a pristine image. We need to think about if we can improve this further without lowering the safety of the current checks significantly. Well, there is also the `-f` option of the update script, but that is asking for troubles if you don't know what you are doing.

**Comment by BaochengSu** [comment]
@jan-kiszka, any comments on the `/etc/another-file` solution? If no problem we will continue on this way.

**Comment by jan-kiszka** [comment]
The key is not "another-file", it's "is this a known to boot image after the update". And that cannot be answered from that file but either from requiring an authentic image (more or less the current situation) or by actually checking what we need to check (kernel image, boot loader, who-knows-what-else).

**Comment by Webbeh** [comment]
Any update system that has to account for changes made by the user since the installation of the "known" image will be a massive pain in the lower back area...

If you want to be sure that the image will boot, there's no other choice than checking that ALL the changes you're gonna make are gonna be applied to files that are known good. 

I think the best option in this particular case is to simply prevent swupdate (unless `--force` flag is set) as soon as `/etc/os-release` is altered.

However, in that case : 
- Add an unavoidable warning to the user that this may prevent the device from booting
- Instruct them on how to update the image properly (pristine image, ...)
- Instruct them on how to recover from such an issue (serial cable) in case they actually attempt the update with the --force flag

I don't know what you think, but if a read-only image is in the works, you're probably better off not losing too much time around this issue.

**Comment by jan-kiszka** [comment]
@BaochengSu still relevent?

**Comment by BaochengSu** [comment]
Don't know... Has anything changed since then?

**Comment by jan-kiszka** [comment]
We have a read-only image recipe with OTA update support by now. The official example image remains on-the-fly customizable  - with all its pros and cons.
